name: Build and Deploy Docker Images

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push analysis service
        uses: docker/build-push-action@v4
        with:
          context: ./analysis_service
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/analysis_service:latest
            ghcr.io/${{ github.repository_owner }}/analysis_service:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Build and push backend service
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/backend_service:latest
            ghcr.io/${{ github.repository_owner }}/backend_service:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max